name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 libboost-all-dev wget libc6-dev libclang-dev pkg-config unzip gcc-8 gcc
      # - name: Install z3
      #   run: |
      #     wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x64-glibc-2.31.zip
      #     unzip z3-4.8.17-x64-glibc-2.31.zip
      #     sudo cp z3-4.8.17-x64-glibc-2.31/include/* /usr/include/
      #     sudo cp z3-4.8.17-x64-glibc-2.31/bin/z3 /usr/bin/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          ref: 9549d8fff7343908228c3e8bedc309d1b83fc204
      - name: Build
        run: |
          mkdir build
          cd build
          
          
          CC="gcc-8" CXX="g++-8" cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          CC="gcc-8" CXX="g++-8" make -j2
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: solc-v0.5.4+commit.9549d8ff
          files: build/solc/solc
