name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Prerequisites
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip gcc g++
      #     
      #     sudo apt-get install -y libboost-all-dev gcc-8 g++-8
      #     
      # - name: Install z3
      #   run: |
      #     wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x64-glibc-2.31.zip
      #     unzip z3-4.8.17-x64-glibc-2.31.zip
      #     sudo cp z3-4.8.17-x64-glibc-2.31/include/* /usr/include/
      #     sudo cp z3-4.8.17-x64-glibc-2.31/bin/z3 /usr/bin/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          submodules: 'recursive'
          ref: e560f70d8e2c7c964df197cf0dd784325b0c6f2f
      - name: Build
        run: |
          mkdir build
          cd build
          
          
          touch ../prerelease.txt
          

          
          mkdir solc
          echo "this is solc binary I swear" > solc/solc


          mv solc/solc ../solc-v0.5.9+commit.e560f70d
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > ./build_artifacts/solc-v0.5.9+commit.e560f70d.md5
          sha256sum -b build/solc/solc | cut -d " " -f1 > ./build_artifacts/solc-v0.5.9+commit.e560f70d.sha256
      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./solc-v0.5.9+commit.e560f70d
          S3_ENDPOINT: 'https://storage.googleapis.com'
          S3_BUCKET: ${{ secrets.BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: solc-v0.5.9+commit.e560f70d
      #     files: |
      #       build/solc/solc
      #       md5.hash
      #       sha256.hash
