name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip gcc g++ awscli
          
          sudo apt-get install -y libboost1.67-all-dev gcc-7 g++-7
          sudo apt-get install -y libjsoncpp-dev
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          submodules: 'recursive'
          ref: f19cddd59e5d5389a47098ab9ae5ec0f1c5213f9
      - name: Build
        run: |
          mkdir build
          cd build
          
          

          sed -i "s/add_compile_options(-Werror)/# add_compile_options(-Werror)/g" ../cmake/EthCompilerSettings.cmake
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          make -j2
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > md5.hash
          sha256sum -b build/solc/solc | cut -d " " -f1 > sha256.hash
      - name: Upload file to bucket
        run: |
          aws configure set aws_secret_access_key ${{ secrets.ACCESS_KEY }}
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY_ID }}
          aws configure set region ""
          aws s3 --endpoint-url https://storage.googleapis.com cp build/solc/solc s3://${{ secrets.BUCKET }}/solc-v0.4.25-nightly.2018.9.6+commit.f19cddd5/solc
          aws s3 --endpoint-url https://storage.googleapis.com cp md5.hash s3://${{ secrets.BUCKET }}/solc-v0.4.25-nightly.2018.9.6+commit.f19cddd5/md5.hash
          aws s3 --endpoint-url https://storage.googleapis.com cp sha256.hash s3://${{ secrets.BUCKET }}/solc-v0.4.25-nightly.2018.9.6+commit.f19cddd5/sha256.hash
