name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip gcc g++
          
          sudo apt-get install -y libboost-all-dev gcc-8 g++-8
          
      # - name: Install z3
      #   run: |
      #     wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x64-glibc-2.31.zip
      #     unzip z3-4.8.17-x64-glibc-2.31.zip
      #     sudo cp z3-4.8.17-x64-glibc-2.31/include/* /usr/include/
      #     sudo cp z3-4.8.17-x64-glibc-2.31/bin/z3 /usr/bin/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          submodules: 'recursive'
          ref: 01f1aaa4c73cd705934a7d769d719ccfc561dd12
      - name: Build
        run: |
          mkdir build
          cd build
          
          
          touch ../prerelease.txt
          

          sed -i "s/add_compile_options(-Werror)/# add_compile_options(-Werror)/g" ../cmake/EthCompilerSettings.cmake
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          make -j2
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > md5.hash
          sha256sum -b build/solc/solc | cut -d " " -f1 > sha256.hash

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: solc-v0.5.14+commit.01f1aaa4
      #     files: |
      #       build/solc/solc
      #       md5.hash
      #       sha256.hash
