name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip
          
          sudo apt-get install -y libboost1.67-all-dev gcc-7 g++-7
          
      # - name: Install z3
      #   run: |
      #     wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x64-glibc-2.31.zip
      #     unzip z3-4.8.17-x64-glibc-2.31.zip
      #     sudo cp z3-4.8.17-x64-glibc-2.31/include/* /usr/include/
      #     sudo cp z3-4.8.17-x64-glibc-2.31/bin/z3 /usr/bin/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          ref: 1e95335589872920b5f13b67731a8eb265f1aef6
      - name: Build
        run: |
          mkdir build
          cd build
          
          

          
          CC="gcc-7" CXX="g++-7" cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          CC="gcc-7" CXX="g++-7" make -j2
          
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > md5.hash
          sha256sum -b build/solc/solc | cut -d " " -f1 > sha256.hash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: solc-v0.4.24-nightly.2018.5.9+commit.1e953355
          files: |
            build/solc/solc
            md5.hash
            sha256.hash
