name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip gcc g++
          
          sudo apt-get install -y libboost-all-dev gcc-8 g++-8
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          submodules: 'recursive'
          ref: e560f70d8e2c7c964df197cf0dd784325b0c6f2f
      - name: Build
        run: |
          mkdir build
          cd build
          
          
          touch ../prerelease.txt
          
          
          mkdir solc
          echo "this is solc binary I swear" > solc/solc
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > md5.hash
          sha256sum -b build/solc/solc | cut -d " " -f1 > sha256.hash
      - name: Upload file to bucket
        run: |
          mkdir ~/.aws
          echo "[default]\naws_access_key_id = ${{ secrets.ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.ACCESS_KEY }}\n" > ~/.aws/credentials  
          aws s3 --endpoint-url https://storage.googleapis.com cp build/solc/solc s3://${{ secrets.BUCKET }}/solc-v0.5.9+commit.e560f70d/solc
          aws s3 --endpoint-url https://storage.googleapis.com cp md5.hash s3://${{ secrets.BUCKET }}/solc-v0.5.9+commit.e560f70d/md5.hash
          aws s3 --endpoint-url https://storage.googleapis.com cp sha256.hash s3://${{ secrets.BUCKET }}/solc-v0.5.9+commit.e560f70d/sha256.hash
